services:
  wardrobe-manager-api:
    image: tmclncy/wardrobemanager-api:latest
    container_name: wardrobe-manager-api
    environment:
      - FrontendUrl=http://localhost:9001
    ports:
      - "9005:8080"
    volumes:
      - ./data:/data
    networks:
      wardrobe-manager:

  wardrobe-manager-presentation:
    image: tmclncy/wardrobemanager-presentation:latest
    container_name: wardrobe-manager-presentation
    environment:
      - BackendUrl=http://localhost:9005
    ports:
      - "9001:80"
    networks:
      wardrobe-manager:

networks:
  wardrobe-manager:
