# This file relies on the source code, it is only meant for development

services:
  wardrobe-manager-api:
    container_name: wardrobe-manager-api
    build:
      context: .
      dockerfile: ./docker/WardrobeManager.Api/Dockerfile
    environment:
      - FrontendUrl=http://localhost:9001
    ports:
      - "9005:8080"
    volumes:
      - ./data:/data

  wardrobe-manager-presentation:
    container_name: wardrobe-manager-presentation
    build:
      context: .
      dockerfile: ./docker/WardrobeManager.Presentation/Dockerfile
    environment:
      - BackendUrl=http://localhost:9005
    ports:
      - "9001:80"
