# This file relies on the source code, it is only meant for development

services:
  wardrobe-manager-api:
    container_name: wardrobe-manager-api
    build:
      context: .
      dockerfile: ./docker/WardrobeManager.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:8000
      - FrontendUrl=http://localhost:9001
#      - Logging__Loglevel__Default=Debug
#      - Logging__Loglevel__Microsoft.AspNetCore=Debug
    ports:
      - "9000:8000"
    volumes:
      - ./data:/data
    networks:
      wardrobe-manager:

  wardrobe-manager-presentation:
    container_name: wardrobe-manager-presentation
    build:
      context: .
      dockerfile: ./docker/WardrobeManager.Presentation/Dockerfile
    environment:
      - BackendUrl=http://localhost:9000
    ports:
      - "9001:80"
    volumes: 
      - ./docker/WardrobeManager.Presentation/nginx.conf:/etc/nginx/nginx.conf
    networks:
      wardrobe-manager:

networks:
  wardrobe-manager:
