name: wardrobemanager
services:
  wardrobe-manager-api:
    image: tmclncy/wardrobemanager-api:latest
    container_name: wardrobe-manager-api
    env_file:
      ./docker/config.env
    ports:
      - "9000:8080"
    volumes:
      - ./data:/data

  wardrobe-manager-presentation:
    image: tmclncy/wardrobemanager-presentation:latest
    container_name: wardrobe-manager-presentation
    env_file:
      ./docker/config.env
    ports:
      - "9001:80"
