# This file relies on the source code, it is only meant for development

services:
  wardrobe-manager-api:
    container_name: wardrobe-manager-api
    build:
      context: .
      dockerfile: ./docker/WardrobeManager.Api/Dockerfile
    environment:
      - FrontendUrl=http://localhost:9001
    ports:
      - "9004:8080"
    volumes:
      - ./data:/data
    networks:
      wardrobe-manager:

  wardrobe-manager-presentation:
    container_name: wardrobe-manager-presentation
    build:
      context: .
      dockerfile: ./docker/WardrobeManager.Presentation/Dockerfile
    ports:
      - "9001:80"
    volumes: 
      - ./docker/WardrobeManager.Presentation/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/appsettings.Production.json:/usr/share/nginx/html/appsettings.Production.json
    networks:
      wardrobe-manager:

networks:
  wardrobe-manager:
