@WardrobeManager.Api_HostAddress = http://localhost:5054

GET {{WardrobeManager.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{WardrobeManager.Api_HostAddress}}/ping
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ink2c1hkTFZSM0NybjczamVCcGFMQyJ9.eyJpc3MiOiJodHRwczovL2Rldi15aGJjdDU4MXJ0MXB0bnVqLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJpeGMzTVBLOXZDb2RXMEhCMGJXR2Y0RVJtR1dxeElPMkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly93YXJkcm9iZW1hbmFnZXIuY29tIiwiaWF0IjoxNzIxMzM3MDE5LCJleHAiOjE3MjE0MjM0MTksInNjb3BlIjoiY2xvdGhpbmc6cmVhZC13cml0ZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6Iml4YzNNUEs5dkNvZFcwSEIwYldHZjRFUm1HV3F4SU8yIn0.Ned4raFeBgRYDIUM0Lgsua33PyfVrDUTzWbUoOJgaK7xR9EF5puN0K5jrZqcDk9YK_B9g08w5cTO0J3mcOhP1pijTeICFysI7C0FL8gWeT0lYKdjEsTaf_Y0OyLODHj1Fp0GJ7tQvqQydZiE1QsFYoXpVkBdt427aFF8gVmJ_fkUBP4Db-S1tfgMHiXr_2J0wZZBZ888qiQ8qS05UBBwewUkKiSxjEudy2_-cgMT9ioq77aLe5KolU259K8MyN9x2m8fajCdKap9cGEwjX4VH4VqoliE5KbISY9a2dYVSEJEgrDYzFu3JInCBnC459GDAoGTZyY3HdoTgL134QFkdw
