// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrobeManager.Api.Database;

#nullable disable

namespace WardrobeManager.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240718154151_Not Sure")]
    partial class NotSure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WardrobeManager.Shared.Models.ServerClothingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DesiredTimesWornBeforeWash")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favourited")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ImageGuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWorn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWornSinceWash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWornTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ClothingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
