name: Docker Image CI

on:
  release:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the WardrobeManager Api Docker Image
      run: docker build . --file docker/WardrobeManager.Api/Dockerfile --tag wardrobe-manager-api:$(date +%s)

    - name: Build WardrobeManager Presentation Docker Image
      run: docker build . --file docker/WardrobeManager.Presentation/Dockerfile --tag wardrobe-manager-presentation:$(date +%s)
    
